version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
        - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
        - VITE_GOOGLE_MAPS_ID=${VITE_GOOGLE_MAPS_ID}
        - VITE_MAPBOX_TOKEN=${VITE_MAPBOX_TOKEN}
    container_name: shopping-list-frontend-local
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3000
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ZENSERP_API_KEY=${ZENSERP_API_KEY}
      - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
      - VITE_GOOGLE_MAPS_ID=${VITE_GOOGLE_MAPS_ID}
      - VITE_MAPBOX_TOKEN=${VITE_MAPBOX_TOKEN}
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}
      - BROWSERBASE_API_KEY=${BROWSERBASE_API_KEY}
      - ENABLE_PLAYWRIGHT=false
      - ENABLE_AI_EXTRACTION=false
      - USE_GOOGLE_SEARCH=false

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: shopping-list-backend-local
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - PORT=3000
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - SERPAPI_KEY=${SERPAPI_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}
      - ZENSERP_API_KEY=${ZENSERP_API_KEY}
      - ENABLE_PLAYWRIGHT=false
      - ENABLE_AI_EXTRACTION=false
      - USE_GOOGLE_SEARCH=false
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3001:3000"

networks:
  app-network:
    driver: bridge 